const categories = [
  { name: 'Biryani', sort_order: 1 },
  { name: 'Regular Thali', sort_order: 2 },
  { name: 'Special Thali', sort_order: 3 },
  { name: 'Rice', sort_order: 4 },
  { name: 'Noodles', sort_order: 5 },
  { name: 'Veg Starter', sort_order: 6 },
  { name: 'Roll', sort_order: 7 },
  { name: 'Roti/Paratha', sort_order: 8 },
  { name: 'Veg Main Course', sort_order: 9 },
  { name: 'Non Veg Main Course', sort_order: 10 },
  { name: 'Combo/Meal for One', sort_order: 11 },
  { name: 'Fish Dishes', sort_order: 12 },
  { name: 'Momo', sort_order: 13 },
  { name: 'Cold Drinks', sort_order: 14 },
  { name: 'Soup', sort_order: 15 },
  { name: 'Tandoor', sort_order: 16 },
  { name: 'Non Veg Starter', sort_order: 17 },
  { name: 'Salad & Sauce & Raita', sort_order: 18 },
  { name: "Flavour's Fried Chicken", sort_order: 19 },
  { name: 'Pure Veg Dishes', sort_order: 20 },
  { name: 'Rice Noodles (Mei-Foon)', sort_order: 21 },
];

const menuItems = {
  1: [
    { name: 'Combo Egg Biryani + Chaap', price: 190, desc: '1000ML, Egg-2Pcs + Alu-2Pcs + Raita, 100Gm Chicken Chaap' },
    { name: 'Combo Chicken Biryani + Chaap', price: 230, desc: '100Gm Chaap, Biryani 1000Ml (Chicken, Egg, Alu, Raita)' },
    { name: 'Tikka Handi Biryani', price: 200, desc: '1000ML, Chicken Tikka-3Pcs + Alu-2Pcs + Rayta' },
    { name: 'Mutton Handi Biryani', price: 270, desc: '1000ML, Alu + Egg + Mutton-200gm + Raita' },
    { name: 'Extra Chicken Piece', price: 75, desc: '150Gm CHK + Alu-1Pcs - No Biryani Rice' },
    { name: 'Chicken Handi Biryani', price: 170, desc: '1000ML, Alu + Egg + Chicken-150gm + Raita' },
    { name: 'Egg Handi Biryani', price: 130, desc: '1000ML, Egg-2Pcs + Alu-2Pcs + Raita' },
    { name: 'Raita', price: 20, desc: '100ML' },
    { name: 'Onion Salad', price: 25, desc: '250ML' },
  ],
  2: [
    { name: 'Regular Veg Thali', price: 100, desc: 'Rice + Dal + Shabji + Bhaji + Chatni + Salad, Pouch & Foil Pack' },
    { name: 'Regular Egg Thali', price: 120, desc: 'Rice + Dal + Shabji + Bhaji + Chatni + Salad + 1 Egg Curry, Pouch & Foil Pack' },
    { name: 'Regular Fish Thali', price: 155, desc: 'Rice + Dal + Shabji + Bhaji + Chatni + Salad + 1 Fish Curry (Katla), Pouch & Foil Pack' },
    { name: 'Regular Chicken Thali', price: 155, desc: 'Rice + Dal + Shabji + Bhaji + Chatni + Salad + Chicken-2 Pcs, Pouch & Foil Pack' },
    { name: 'Regular Mutton Thali', price: 240, desc: 'Rice + Dal + Shabji + Bhaji + Chatni + Salad + Mutton-2Pcs' },
    { name: 'Regular Pabda Thali', price: 210, desc: 'Rice + Dal + Shabji + Bhaji + Chatni + Salad + Pabda-2Pcs, Pouch & Foil Pack' },
    { name: 'Regular Prawn Thali', price: 210, desc: 'Rice + Dal + Shabji + Bhaji + Chatni + Salad + Prawn-2Pcs, Pouch & Foil Pack' },
    { name: 'Regular Veg Thali - Roti', price: 100, desc: 'Rice + Roti + Dal + Shabji + Bhaji + Chatni + Salad' },
    { name: 'Regular Egg Thali - Roti', price: 120, desc: 'Rice + Roti + Dal + Shabji + Bhaji + Chatni + Salad + 1 Egg Curry' },
    { name: 'Regular Chicken Thali - Roti', price: 155, desc: 'Rice + Roti + Dal + Shabji + Bhaji + Chatni + Salad + Chicken-2 Pcs' },
    { name: 'Regular Fish Thali - Roti', price: 155, desc: 'Rice + Roti + Dal + Shabji + Bhaji + Chatni + Salad + 1 Fish Curry' },
    { name: 'Regular Mutton Thali - Roti', price: 225, desc: 'Rice + Roti + Dal + Shabji + Bhaji + Chatni + Salad + Mutton-2Pcs' },
    { name: 'Jhuri Alu Bhaja', price: 75, desc: 'Crispy potato' },
    { name: 'Shabji Dal', price: 50, desc: 'Mixed vegetable dal' },
    { name: 'Regular Shabji', price: 50, desc: 'Seasonal vegetable' },
  ],
  3: [
    { name: 'Special Veg Thali', price: 200, desc: 'Rice + Roti-1 + Dal + Shabji + Bhaji + Chatni + Salad + Paneer-3 + Papad + Rayta + Sweet, 5CP PVC Pack' },
    { name: 'Special Egg Thali', price: 175, desc: 'Rice + Roti-1 + Dal + Shabji + Bhaji + Chatni + Salad + Egg-2 + Papad + Rayta + Sweet, 5CP PVC Pack' },
    { name: 'Special Fish Thali', price: 190, desc: 'Rice + Roti-1 + Dal + Shabji + Bhaji + Chatni + Salad + Fish (Large Size) + Papad + Rayta + Sweet, 5CP PVC Pack' },
    { name: 'Special Chicken Thali', price: 200, desc: 'Rice + Roti-1 + Dal + Shabji + Bhaji + Chatni + Salad + Chk-3Pcs + Papad + Rayta + Sweet, 5CP PVC Pack' },
    { name: 'Special Veg Thali - Roti', price: 200, desc: 'Roti-4 + Dal + Shabji + Bhaji + Chatni + Salad + Paneer-3 + Papad + Rayta + Sweet, 5CP PVC Pack' },
    { name: 'Special Egg Thali - Roti', price: 175, desc: 'Roti-4 + Dal + Shabji + Bhaji + Chatni + Salad + Egg-2 + Papad + Rayta + Sweet, 5CP PVC Pack' },
    { name: 'Special Fish Thali - Roti', price: 190, desc: 'Roti-4 + Dal + Shabji + Bhaji + Chatni + Salad + Fish (Large) + Papad + Rayta + Sweet, 5CP PVC Pack' },
    { name: 'Special Chicken Thali - Roti', price: 200, desc: 'Roti-4 + Dal + Shabji + Bhaji + Chatni + Salad + Chk-3Pcs + Papad + Rayta + Sweet, 5CP PVC Pack' },
    { name: 'Jhuri Alu Bhaja', price: 75, desc: 'Crispy potato' },
  ],
  4: [
    { name: 'Steamed Rice', price: 50, desc: '750 ML' },
    { name: 'Jeera Rice', price: 90, desc: '750 ML' },
    { name: 'Sweet Pulao', price: 150, desc: '750 ML' },
    { name: 'Veg Fried Rice', price: 90, desc: '750 ML' },
    { name: 'Egg Fried Rice', price: 105, desc: '750 ML' },
    { name: 'Chicken Fried Rice', price: 130, desc: '750 ML' },
    { name: 'Egg Chicken Fried Rice', price: 145, desc: '750 ML' },
    { name: 'Mushroom Fried Rice', price: 130, desc: '750 ML' },
    { name: 'Paneer Fried Rice', price: 130, desc: '750 ML' },
    { name: 'Prawn Fried Rice', price: 150, desc: '750 ML' },
    { name: 'Mixed Fried Rice', price: 190, desc: '750 ML, Egg + Chicken + Prawn' },
    { name: 'Schezwan Veg Fried Rice', price: 105, desc: '750 ML' },
    { name: 'Schezwan Egg Fried Rice', price: 120, desc: '750 ML' },
    { name: 'Schezwan Chicken Fried Rice', price: 145, desc: '750 ML' },
    { name: 'Schezwan Egg Chicken Fried Rice', price: 160, desc: '750 ML' },
    { name: 'Schezwan Mushroom Fried Rice', price: 145, desc: '750 ML' },
    { name: 'Schezwan Paneer Fried Rice', price: 145, desc: '750 ML' },
    { name: 'Schezwan Prawn Fried Rice', price: 165, desc: '750 ML' },
    { name: 'Schezwan Mixed Fried Rice', price: 205, desc: 'Prawn + Egg + Chicken, 750 ML' },
  ],
  5: [
    { name: 'Veg Noodles', price: 90, desc: '750 ML' },
    { name: 'Egg Noodles', price: 105, desc: '750 ML' },
    { name: 'Chicken Noodles', price: 130, desc: '750 ML' },
    { name: 'Egg Chicken Noodles', price: 145, desc: '750 ML' },
    { name: 'Mushroom Noodles', price: 130, desc: '750 ML' },
    { name: 'Paneer Noodles', price: 130, desc: '750 ML' },
    { name: 'Prawn Noodles', price: 150, desc: '750 ML' },
    { name: 'Mixed Noodles', price: 190, desc: 'Prawn + Egg + Chicken, 750 ML' },
    { name: 'Schezwan Veg Noodles', price: 105, desc: '750 ML' },
    { name: 'Schezwan Egg Noodles', price: 120, desc: '750 ML' },
    { name: 'Schezwan Chicken Noodles', price: 145, desc: '750 ML' },
    { name: 'Schezwan Egg Chicken Noodles', price: 160, desc: '750 ML' },
    { name: 'Schezwan Mushroom Noodles', price: 145, desc: '750 ML' },
    { name: 'Schezwan Paneer Noodles', price: 145, desc: '750 ML' },
    { name: 'Schezwan Prawn Noodles', price: 165, desc: '750 ML' },
    { name: 'Schezwan Mixed Noodles', price: 205, desc: 'Prawn + Egg + Chicken, 750 ML' },
    { name: 'Chilli Garlic Egg Noodles', price: 125, desc: 'Chilli Garlic Egg Noodles' },
    { name: 'Chilli Garlic Veg Noodles', price: 110, desc: 'Chilli Garlic Veg Noodles' },
    { name: 'Chilli Garlic Chicken Noodles', price: 150, desc: 'Chilli Garlic Chicken Noodles' },
    { name: 'Chilli Garlic Egg Chicken Noodles', price: 165, desc: 'Chilli Garlic Egg Chicken Noodles' },
    { name: 'Chilli Garlic Mixed Noodles', price: 210, desc: 'Chilli Garlic Egg, Chicken, Prawn Noodles' },
  ],
  6: [
    { name: 'Paneer Pakada', price: 150, desc: '6 Pcs with two Dips' },
    { name: 'Dry Veg Manchurian', price: 140, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Dry Chilli Veg Ball', price: 140, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Crispy Baby Corn', price: 170, desc: 'Dry 500ML (Spicy/Non Spicy)' },
    { name: 'Dry Chilli Mushroom', price: 180, desc: '500ML (Spicy/Non Spicy)' },
    { name: 'Dry Chilli Paneer', price: 180, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Soya Chaap Pakada', price: 150, desc: '6 Pcs Soya Chaap Pakada' },
    { name: 'Chilli Honey Potato', price: 160, desc: '500 ML, Crispy Starter' },
  ],
  7: [
    { name: 'Double Egg Roll', price: 50, desc: 'Classic double egg roll' },
    { name: 'Chicken Roll', price: 75, desc: 'Chicken roll' },
    { name: 'Mushroom Roll', price: 75, desc: 'Mushroom roll' },
    { name: 'Paneer Roll', price: 75, desc: 'Paneer roll' },
    { name: 'Egg Chicken Roll', price: 90, desc: 'Egg + Chicken roll' },
    { name: 'Double Egg Chicken Roll', price: 105, desc: 'Double egg + Chicken roll' },
    { name: 'Chicken Healthy Wrap (Oil Free)', price: 85, desc: 'Wrap with Tikka Kabab in Tandoori Roti' },
    { name: 'Paneer Healthy Wrap (Veg)', price: 85, desc: 'Wrap with Paneer' },
  ],
  8: [
    { name: 'Lachha Paratha', price: 25, desc: 'Classic layered paratha' },
    { name: 'Alu Paratha', price: 100, desc: '2 Pcs With Salad & Sauce + Raita' },
    { name: 'Paneer Paratha', price: 120, desc: '2 Pcs With Salad & Sauce + Raita' },
    { name: 'Egg Mughlai Paratha', price: 100, desc: 'Shabji + Salad + Sauce, Egg' },
    { name: 'Chicken Mughlai Paratha', price: 140, desc: 'Shabji + Salad + Sauce, Egg + Chk' },
    { name: 'Tawa Roti', price: 6, desc: 'Single roti' },
    { name: 'Butter Roti', price: 12, desc: 'Butter roti' },
    { name: 'Tandoori Roti', price: 17, desc: '1 PC' },
    { name: 'Butter Tandoori Roti', price: 24, desc: '1 Pcs' },
    { name: 'Plain Naan', price: 27, desc: '2 Slices' },
    { name: 'Butter Naan', price: 37, desc: '2 Slices' },
    { name: 'Garlic Naan', price: 47, desc: '2 Slices' },
    { name: 'Masala Kulcha', price: 47, desc: '2 Slices' },
    { name: 'Atta Tandoori Roti', price: 20, desc: 'Made with Atta' },
    { name: 'Atta Lachha Paratha', price: 30, desc: 'Made with Atta, Prepared in Tandoor' },
  ],
  9: [
    { name: 'Alu Bhaja', price: 65, desc: 'Crispy potato' },
    { name: 'Alu Dum', price: 100, desc: '6 Pcs (Non Spicy)' },
    { name: 'Dal Tadka', price: 90, desc: '500ML (Spicy/Non Spicy)' },
    { name: 'Dal Fry', price: 100, desc: 'Added Makhana 500ML (Spicy/Non Spicy)' },
    { name: 'Chana Masala', price: 110, desc: '500ML (Spicy/Non Spicy)' },
    { name: 'Mixed Veg', price: 110, desc: '500ML (Non Spicy)' },
    { name: 'Veg Manchurian', price: 140, desc: '6 Pcs Gravy (Spicy/Non Spicy)' },
    { name: 'Baby Corn Chilli (Gravy)', price: 170, desc: '500ML Gravy (Spicy/Non Spicy)' },
    { name: 'Baby Corn Manchurian', price: 170, desc: 'Gravy 500ML (Spicy/Non Spicy)' },
    { name: 'Paneer Chilli', price: 180, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Paneer Manchurian', price: 180, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Garlic Paneer', price: 180, desc: 'Medium Spicy 6 Pcs' },
    { name: 'Paneer Do Piyaza', price: 180, desc: '6 Pcs (Non Spicy)' },
    { name: 'Kadhai Paneer', price: 180, desc: '6 Pcs (Spicy)' },
    { name: 'Paneer Bhuna Masala', price: 190, desc: 'Shredded Paneer 500ML (Spicy)' },
    { name: 'Paneer Kashmiri', price: 200, desc: '6 Pcs (Mid Spicy)' },
    { name: 'Matar Paneer', price: 200, desc: '6 Pcs (Non Spicy)' },
    { name: 'Paneer Butter Masala (6 Pcs)', price: 200, desc: '6 Pcs (Non Spicy)' },
    { name: 'Mushroom Chilli', price: 180, desc: '500ML (Spicy/Non Spicy)' },
    { name: 'Mushroom Manchurian', price: 180, desc: '500ML (Spicy/Non Spicy)' },
    { name: 'Mushroom Masala', price: 180, desc: '500ML (Spicy/Non Spicy)' },
    { name: 'Kadhai Mushroom', price: 180, desc: '500ML (Spicy)' },
    { name: 'Mushroom Do Piyaza', price: 180, desc: '500ML (Non Spicy)' },
    { name: 'Matar Mushroom Masala', price: 200, desc: '500ML (Non Spicy)' },
    { name: 'Soya Chaap Curry', price: 170, desc: '6 Pcs Soya Chaap + Alu + Gravy' },
    { name: 'Soya Chaap Chilli', price: 170, desc: '6 Pcs Gravy (Soya Chaap)' },
    { name: 'Soya Chaap Manchurian', price: 170, desc: '6 Pcs Soya Chaap Manchurian' },
    { name: 'Jhuri Alu Bhaja', price: 75, desc: '450ML' },
    { name: 'Veg Dal (Mung/Arhar)', price: 50, desc: '500ML' },
    { name: 'Hot Garlic Paneer', price: 180, desc: '6 Pcs (Spicy)' },
    { name: 'Garlic Paneer Sweet', price: 180, desc: 'Sweet 6 Pcs (Non Spicy)' },
    { name: 'Alu Bhaja (500ML)', price: 65, desc: '500 ML' },
  ],
  10: [
    { name: 'Egg Curry', price: 60, desc: '2 Eggs' },
    { name: 'Egg Tadka', price: 105, desc: '500ML (Spicy/Non Spicy)' },
    { name: 'Double Egg Tadka', price: 120, desc: 'Double Egg 500ML (Spicy/Non Spicy)' },
    { name: 'Chicken Tadka', price: 130, desc: 'Chicken, 500ML (Spicy/Non Spicy)' },
    { name: 'Egg Chicken Tadka', price: 145, desc: 'Egg + Chicken 500ML (Spicy/Non Spicy)' },
    { name: 'Chicken Kasa', price: 170, desc: '4 Pcs (Thick Gravy Spicy)' },
    { name: 'Chicken Curry', price: 170, desc: '4 Pcs (Spicy/Non Spicy)' },
    { name: 'Chicken Do Piyaza', price: 180, desc: '4 Pcs (Non Spicy)' },
    { name: 'Kadhai Chicken', price: 180, desc: '4 Pcs (Spicy)' },
    { name: 'Chicken Bhuna Masala', price: 200, desc: 'Shredded 500ML (Spicy)' },
    { name: 'Chicken Black Pepper', price: 180, desc: '4 Pcs (Non Spicy)' },
    { name: 'Methi Chicken', price: 180, desc: '4 Pcs (Non Spicy)' },
    { name: 'Chicken Bharta', price: 200, desc: 'Shredded Chicken 500ML (Non Spicy)' },
    { name: 'Chicken Butter Masala', price: 200, desc: '4 Pcs (Non Spicy)' },
    { name: 'Chicken Tikka Masala', price: 200, desc: '4 Pcs (Spicy)' },
    { name: 'Chicken Tikka Butter Masala', price: 220, desc: '4 Pcs (Non Spicy)' },
    { name: 'Chicken Handi', price: 280, desc: '6 Pcs + Alu + Egg (Spicy/Non Spicy)' },
    { name: 'Tandoori Chicken Masala', price: 350, desc: '4 Pcs/Half Tandoori (Spicy)' },
    { name: 'Chilli Chicken', price: 190, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Garlic Chicken', price: 190, desc: '6 Pcs (Mid Spicy)' },
    { name: 'Garlic Chicken Sweet', price: 190, desc: '6 Pcs (Sweet Gravy)' },
    { name: 'Garlic Chicken Hot', price: 190, desc: '6 Pcs (Extra Spicy Gravy)' },
    { name: 'Chicken Manchurian', price: 190, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Chicken Schezwan', price: 190, desc: '6 Pcs (Spicy)' },
    { name: 'Mutton Kasa', price: 270, desc: '4 Pcs (Spicy/Non Spicy)' },
    { name: 'Mutton Curry', price: 270, desc: '4 Pcs (Spicy/Non Spicy)' },
    { name: 'Mutton Handi', price: 400, desc: '6 Pcs + Alu + Egg (Spicy/Non Spicy)' },
    { name: 'Kancha Lanka Murg', price: 200, desc: '4 PCs (Spicy)' },
    { name: 'Omelette', price: 40, desc: 'Double Egg' },
  ],
  11: [
    { name: 'Dal Tadka Combo (Roti)', price: 90, desc: 'Roti-4 Pcs + Dal Tadka 300ML' },
    { name: 'Egg Tadka Combo (Roti)', price: 95, desc: 'Roti-4 Pcs + Egg Tadka 300ML' },
    { name: 'Alu Dum Combo (Roti)', price: 90, desc: 'Roti-4 Pcs + Alu Dum-3 Pcs' },
    { name: 'Alu Dum Combo (Paratha)', price: 110, desc: 'Paratha-2 Pcs + Alu Dum-3 Pcs' },
    { name: 'Chicken Curry Combo (Roti)', price: 140, desc: 'Roti-4 Pcs + Chicken Curry-2/3 Pcs' },
    { name: 'Chicken Curry Combo (Rice)', price: 140, desc: 'Rice + Chicken Curry-2/3' },
    { name: 'Paneer Masala Combo (Roti)', price: 140, desc: 'Roti-4 Pcs + Paneer-3 Pcs' },
    { name: 'Paneer Masala Combo (Tandoori Roti)', price: 150, desc: 'Tandoori Roti-2 Pcs + Paneer-3 Pcs' },
    { name: 'Paneer Masala Combo (Jeera Rice)', price: 170, desc: 'Jeera Rice + Paneer-3 Pcs' },
    { name: 'Tikka Masala Combo (Roti)', price: 140, desc: 'Roti-4 Pcs + Chicken Tikka-2 Pcs' },
    { name: 'Tikka Masala Combo (Tandoori Roti)', price: 150, desc: 'Tandoori Roti-2 Pcs + Chicken Tikka-2 Pcs' },
    { name: 'Tikka Masala Combo (Jeera Rice)', price: 170, desc: 'Jeera Rice + Chicken Tikka-2 Pcs' },
    { name: 'Chilli Chicken Combo (Tandoori Roti)', price: 150, desc: 'Tandoori Roti 2 Pcs + Chilli Chicken 3 Pcs' },
    { name: 'Chilli Chicken Combo (Paratha)', price: 160, desc: 'Paratha-2 Pcs + Chilli Chicken-3 Pcs' },
    { name: 'Noodles Combo (Chilli Chicken)', price: 170, desc: 'Chilli Chicken-3 Pcs + Veg Noodles' },
    { name: 'Noodles Combo (Chilli Paneer)', price: 170, desc: 'Chilli Paneer-3 Pcs + Veg Noodles' },
    { name: 'Fried Rice Combo (Chilli Chicken)', price: 170, desc: 'Chilli Chicken-3 Pcs + Veg Fried Rice' },
    { name: 'Fried Rice Combo (Chilli Paneer)', price: 170, desc: 'Chilli Paneer-3 Pcs + Veg Fried Rice' },
    { name: 'Chilli Paneer Combo (Paratha)', price: 160, desc: 'Paratha-2 PCs + Chilli Paneer 3 Pcs' },
    { name: 'Chilli Paneer Combo (Tandoori Roti)', price: 160, desc: 'Tandoori Roti 2 PCs + Chilli Paneer 3 Pcs' },
    { name: 'Chilli Paneer Combo (Tawa Roti)', price: 150, desc: 'Tawa Roti-4 + Paneer-3 Pcs' },
    { name: 'Chilli Chicken Combo (Tawa Roti)', price: 150, desc: 'Tawa Roti-4 + Chilli Chicken-3' },
    { name: 'Chicken Chaap Combo (Paratha)', price: 130, desc: 'Chaap 100gm, Laccha Paratha-2 Pcs' },
  ],
  12: [
    { name: 'Fish Curry', price: 90, desc: 'Katla 1 Pc - 140Gm (Spicy)' },
    { name: 'Fish Sarshe', price: 100, desc: 'Katla 1 Pc - 140Gm (Spicy)' },
    { name: 'Fish Kalia', price: 100, desc: '1 Pc - 140Gm (Spicy)' },
    { name: 'Dahi Katla', price: 110, desc: '1 Pc - 140Gm (Non Spicy)' },
    { name: 'Pabda Sarshe', price: 130, desc: '2 Pcs (Spicy), Added Mustard Paste' },
    { name: 'Garlic Fish Gravy', price: 240, desc: '6 Pcs Gravy, Bhetki' },
    { name: 'Chilli Fish Gravy', price: 240, desc: '6 Pcs (Spicy/Non Spicy) Gravy, Bhetki' },
    { name: 'Fish Manchurian Gravy', price: 240, desc: 'Gravy 6 Pcs (Spicy/Non Spicy), Bhetki' },
    { name: 'Prawn Masala', price: 220, desc: '4 Pcs (Spicy)' },
    { name: 'Prawn Malai Curry', price: 220, desc: '4 Pcs (Non Spicy)' },
    { name: 'Fish Finger', price: 200, desc: '5 Pcs, Bhetki' },
    { name: 'Fish Fry', price: 120, desc: 'Bhetki' },
  ],
  13: [
    { name: 'Chicken Momo Steamed (6 Pcs)', price: 90, desc: '6 Pcs, with Soup' },
    { name: 'Chicken Momo Fried (6 Pcs)', price: 100, desc: '6 Pcs, No Soup' },
    { name: 'Chicken Momo Pan Fried (6 Pcs)', price: 130, desc: '6 Pcs, No Soup' },
    { name: 'Chicken Momo Tandoor', price: 130, desc: '6 Pcs, No Soup' },
  ],
  14: [
    { name: 'Water 1 Ltr', price: 25, desc: '1000ML' },
    { name: '750ML Coke', price: 50, desc: '750ML, Coke Only' },
  ],
  15: [
    { name: 'Chicken Hot & Sour Soup', price: 100, desc: '500ML, Added Chicken & Egg & Veggies' },
    { name: 'Veg Hot & Sour Soup', price: 100, desc: 'Carrots, cabbage, mushrooms, paneer' },
  ],
  16: [
    { name: 'Tandoori Egg', price: 130, desc: '5 Pcs (Spicy)' },
    { name: 'Chicken Tangri Kabab', price: 200, desc: '2 Pcs (Non Spicy)' },
    { name: 'Chicken Tikka Kabab', price: 240, desc: '6 Pcs (Spicy)' },
    { name: 'Chicken Reshmi Kabab (6 Pcs)', price: 250, desc: '6 Pcs (Non Spicy)' },
    { name: 'Paneer Tikka', price: 210, desc: '6 Pcs (Spicy)' },
    { name: 'Chicken Malai Kabab', price: 270, desc: '6 Pcs (Non Spicy)' },
    { name: 'Chicken Cheese Kabab', price: 270, desc: '6 Pcs (Non Spicy)' },
    { name: 'Chicken Afghani Kabab', price: 260, desc: '6 Pcs (Spicy)' },
    { name: 'Chicken Banjara Kabab (6 Pcs)', price: 260, desc: '6 Pcs (Spicy)' },
    { name: 'Chicken Achari Kabab', price: 260, desc: '6 Pcs (Spicy)' },
    { name: 'Kabab Tawa Fry', price: 220, desc: '15 Pcs Small Kabab fried with Capsicum & Onion' },
    { name: 'Soya Chaap Tikka Kabab', price: 180, desc: '6 Pcs, Soya Chaap Tikka' },
    { name: 'Tandoori Chicken (Full)', price: 480, desc: '4 Pcs' },
    { name: 'Tandoori Chicken (Half)', price: 250, desc: '2 Pcs' },
    { name: 'Lasoni Kabab Chicken', price: 260, desc: '6 Pcs' },
    { name: 'Chicken Seekh Kabab', price: 160, desc: '6 Pcs' },
    { name: 'Green Chatni (Tandoori)', price: 10, desc: '35ML' },
    { name: 'Sunheri Kabab', price: 260, desc: '6 Pcs' },
  ],
  17: [
    { name: 'Fish Fry', price: 120, desc: '1 Pc Bhetki' },
    { name: 'Fish Finger', price: 200, desc: '5 Pcs Bhetki' },
    { name: 'Chicken Pakada', price: 160, desc: '6 Pcs with two Dips' },
    { name: 'Schezwan Egg Dry', price: 140, desc: '8 Pcs (Spicy)' },
    { name: 'Dry Chilli Chicken (6 Pcs)', price: 190, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Dry Garlic Chicken', price: 190, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Chicken Lollipop/Drums of Heaven', price: 210, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Dry Chilli Fish', price: 230, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Dry Garlic Fish', price: 230, desc: '6 Pcs (Spicy/Non Spicy)' },
    { name: 'Chicken 65', price: 200, desc: 'Spicy Starter' },
    { name: 'Chili Garlic Pepper Chicken', price: 200, desc: 'Crispy Chicken, 500 ML' },
    { name: 'Salt & Pepper Chicken', price: 200, desc: '500ML, Chinese Starter' },
  ],
  18: [
    { name: 'Green Salad', price: 35, desc: '450ML' },
    { name: 'Onion Salad', price: 25, desc: '250ML' },
    { name: 'Green Chatni (Tandoori)', price: 10, desc: '35ML' },
    { name: 'Sauce Dip (Schezwan)', price: 20, desc: '35ML' },
    { name: 'Raita', price: 20, desc: '100ML' },
    { name: 'Mayonnaise', price: 10, desc: '35ML' },
    { name: 'Tomato Ketchup', price: 10, desc: '35ML' },
    { name: 'Momo Sauce', price: 10, desc: '35ML' },
  ],
  19: [
    { name: 'Chicken Popcorn', price: 140, desc: '250ML Foil Full' },
    { name: 'Chicken Strips', price: 160, desc: '6 PCS' },
    { name: 'Crispy Chicken Wings', price: 170, desc: '6 Pcs' },
  ],
  20: [
    { name: 'Pure Veg - Dal Fry', price: 90, desc: 'Without Garlic & Onion' },
    { name: 'Pure Veg - Alu Dum', price: 120, desc: 'Without Garlic & Onion, 6 Pcs Alu' },
    { name: 'Pure Veg - Paneer Masala', price: 200, desc: 'Without Garlic & Onion, 6 Pcs Paneer, Spicy' },
    { name: 'Pure Veg - Soya Chaap Curry', price: 170, desc: '6 Pcs, Without Garlic & Onion' },
    { name: 'Pure Veg - Pulao Alu Dum Combo', price: 160, desc: 'Pulao + 3 Pcs Alu Dum' },
    { name: 'Pure Veg - Roti Paneer Masala Combo', price: 150, desc: '3 Pcs Paneer + 4 Roti' },
  ],
  21: [
    { name: 'Rice Noodles Veg (Mei-Foon)', price: 125, desc: 'Rice Noodles Veg' },
    { name: 'Rice Noodles Egg (Mei-Foon)', price: 140, desc: 'Egg Rice Noodles' },
    { name: 'Rice Noodles Chicken (Mei-Foon)', price: 165, desc: 'Rice Noodles Chicken' },
    { name: 'Rice Noodles Egg Chicken (Mei-Foon)', price: 180, desc: 'Rice Noodles Egg Chicken' },
    { name: 'Rice Noodles Mixed (Mei-Foon)', price: 220, desc: 'Egg, Chicken, Prawn' },
    { name: 'Schezwan Rice Noodles Mixed (Mei-Foon)', price: 235, desc: 'Schezwan Egg, Chicken, Prawn' },
    { name: 'Schezwan Rice Noodles Egg Chicken (Mei-Foon)', price: 195, desc: 'Schezwan Egg Chicken' },
    { name: 'Schezwan Rice Noodles Chicken (Mei-Foon)', price: 180, desc: 'Schezwan Chicken' },
    { name: 'Schezwan Rice Noodles Egg (Mei-Foon)', price: 155, desc: 'Schezwan Egg' },
    { name: 'Schezwan Rice Noodles Veg (Mei-Foon)', price: 140, desc: 'Schezwan Veg' },
    { name: 'Rice Noodles Mushroom (Mei-Foon)', price: 165, desc: 'Mushroom Rice Noodles' },
    { name: 'Rice Noodles Paneer (Mei-Foon)', price: 165, desc: 'Rice Noodles Paneer' },
  ],
};

module.exports = { categories, menuItems };
